/* build.js — concatenate the shared core modules into a single app.core.js so
   each page makes one request instead of 13. These 13 files are loaded in this
   exact order, and all present, on every entry point (index/read/test), so they
   bundle cleanly. Page-specific scripts (config, vendor, settings, pull, notify)
   stay separate.

   Run after editing any core module:  node build.js
   Then bump the CACHE version in sw.js so clients pick up the new bundle. */
'use strict';
const fs = require('fs');
const path = require('path');

const CORE = [
  'i18n.js', 'tripdata.js', 'itinerary.js', 'map.js', 'features.js',
  'weather.js', 'stats.js', 'route.js', 'gallery.js', 'notes.js',
  'enrichdata.js', 'enrich.js', 'welcome.js',
];

const OUT = 'app.core.js';
const dir = __dirname;

let out = '/* app.core.js — GENERATED by build.js. Do not edit directly.\n' +
  '   Edit the source modules and re-run `node build.js`.\n' +
  '   Bundled (in order): ' + CORE.join(', ') + ' */\n';

for (const f of CORE) {
  const src = fs.readFileSync(path.join(dir, f), 'utf8');
  out += '\n/* ==================== ' + f + ' ==================== */\n' + src;
  if (!src.endsWith('\n')) out += '\n';
}

fs.writeFileSync(path.join(dir, OUT), out);
console.log('Wrote ' + OUT + ' (' + CORE.length + ' modules, ' + out.length + ' bytes)');
